// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALpaNn5-iLml0WFtpAsnrIXF_EatJK6U0',
    appId: '1:5096473566:web:6d951941a568ab7a53934f',
    messagingSenderId: '5096473566',
    projectId: 'clone-ca758',
    authDomain: 'clone-ca758.firebaseapp.com',
    databaseURL: 'https://clone-ca758-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clone-ca758.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbcruVw7KF1n2zNaPFcKaUGv3e9vAT6AU',
    appId: '1:5096473566:android:6caac6055317d92053934f',
    messagingSenderId: '5096473566',
    projectId: 'clone-ca758',
    databaseURL: 'https://clone-ca758-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clone-ca758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaOLTumr6tBnBrsWPTTqX2XOR02PFAm4Q',
    appId: '1:5096473566:ios:a6e789a7d482827653934f',
    messagingSenderId: '5096473566',
    projectId: 'clone-ca758',
    databaseURL: 'https://clone-ca758-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clone-ca758.appspot.com',
    androidClientId: '5096473566-q4ha8q42p4mul128js84a877ldimok5m.apps.googleusercontent.com',
    iosClientId: '5096473566-b90im6gosk5n7ggiepbdtkmcc2sgr0fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmailClone',
  );
}
